graph TD
  .csv --> Import
  API --> Import
  DBI --> Import
  dbplyr --> Import
  Import -.-> Format[Format for analysis]
  Format -.-> Tidy

  subgraph r4ds
  Import ==> Tidy
  Tidy ==> Transform
  Transform ==> Visualize
  Visualize ==> Model
  Model -.-> Transform
  Visualize ==> Communicate
  end

  Visualize -.-> FormatComm[Format for communication]
  FormatComm -.-> Communicate

  FormatComm -- Apply formatting early --> Format

  dbplyr -.-> Tidy
  dbplyr -.-> Transform
  dbplyr -.-> Visualize

  Communicate --> gt
  Communicate --> ggplot2
  Communicate --> DT
  Communicate --> plotly
