name: "Action to determine extra packages to be installed"
outputs:
  packages:
    description: "List of extra packages"
    value: ${{ steps.get-extra.outputs.packages }}

runs:
  using: "composite"
  steps:
    - name: Get extra packages
      id: get-extra
      run: |
        set -x
        packages=$( ( grep Config/gha/extra-packages DESCRIPTION || true ) | cut -d " " -f 2)
        echo packages=$packages >> $GITHUB_OUTPUT
      shell: bash
