dir.create("vignettes", showWarnings = FALSE)
for (file in list.files(
  "../../vignettes",
  pattern = "[.]Rmd$",
  full.names = TRUE
)) {
  text <- readLines(file)
  text <- c(
    text[1],
    "# Generated by helper-sync.R, do not edit by hand",
    text[-1]
  )
  writeLines(text, file.path("vignettes", basename(file)))
}
