# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

shallow_copy <- function(data) {
    .Call('tibble_shallow_copy', PACKAGE = 'tibble', data)
}

as_regular_df <- function(df) {
    .Call('tibble_as_regular_df', PACKAGE = 'tibble', df)
}

