name: Cancel
on:
  workflow_run:
    workflows: ["rcc", "Continuous Benchmarks", "pkgdown", "test-coverage"]
    types:
      - requested
jobs:
  cancel:
    runs-on: ubuntu-latest
    steps:
    - uses: styfle/cancel-workflow-action@0.9.0
      with:
        workflow_id: ${{ github.event.workflow.id }}
